pipeline{
    agent any
    stages{
        stage("Checkout"){
			steps{
				withCredentials([usernamePassword(credentialsId: 'docker-hub',usernameVariable: 'DOCKERHUB_USER',passwordVariable: 'DOCKERHUB_PASSWORD')]){
					sh script: "docker login -u  ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}"
				}
			}
        }
		stage("Build and Run"){
			steps{
				sh script: "cd jenkins/CI"
				sh script: "docker-compose up -d"
			}
		}
        stage("Finalize"){
			steps{
				sh script: "cd jenkins/CI"
				sh script: 'docker-compose push'
			}
        }
    }
}